FROM openjdk:11
MAINTAINER "Chandu Velagapudi"
COPY target/dickerproject-deployment-0.0.1-SNAPSHOT.jar /usr/app/
WORKDIR /usr/app/
EXPOSE 9895
ENTRYPOINT ["java", "-jar", "spring-boot-docker-app.jar"]